### ISSUE TITLE
A few colophon tweaks

### ISSUE THREAD

**Issue by robinwhittleton** [PhenomenJan/james-stephens_irish-fairy-tales#2]
- `Jan Genoch` ➡️ `<b class="name">Jan Genoch</b>`
- `A. Elizabeth Warren` ➡️ `<abbr>A.</abbr> Elizabeth Warren`
- a painting completed in 1850-1900 ➡️ a painting completed between 1850-1900

**Comment by PhenomenJan** [comment]
Fixed in https://github.com/PhenomenJan/james-stephens_irish-fairy-tales/commit/a0c3a4516d278ccf6b7a8b6a1ee54373a66a60b6
