### ISSUE TITLE
Remove classes from the dedication

### ISSUE THREAD

**Issue by robinwhittleton** [PhenomenJan/james-stephens_irish-fairy-tales#3]
Generally we can avoid classes. For the dedication we can drop them, and style with `section[epub|type~="dedication"] p span:nth-child(even)` instead.

**Comment by PhenomenJan** [comment]
Fixed in https://github.com/PhenomenJan/james-stephens_irish-fairy-tales/commit/a0c3a4516d278ccf6b7a8b6a1ee54373a66a60b6
