### ISSUE TITLE
Editorial spelling correction in the-little-brawl-at-allen

### ISSUE THREAD

**Issue by robinwhittleton** [PhenomenJan/james-stephens_irish-fairy-tales#5]
`<i xml:lang="fr">mêlée</i>` ➡️ `melee`

This is a modernisation, so should be an [Editorial] commit.

**Comment by PhenomenJan** [comment]
Fixed in https://github.com/PhenomenJan/james-stephens_irish-fairy-tales/commit/701e8efa46722a45cb2ec3377ee92a3632036458
