### ISSUE TITLE
Editorial spelling correction in mongans-frenzy

### ISSUE THREAD

**Issue by robinwhittleton** [PhenomenJan/james-stephens_irish-fairy-tales#6]
`à propos` ➡️ `apropos`

This is a modernisation, so should be an [Editorial] commit.

**Comment by PhenomenJan** [comment]
Fixed in https://github.com/PhenomenJan/james-stephens_irish-fairy-tales/commit/1f9744a86e82bcb931a34262fed0568b123c99ee
